config/routes.rb
Phototagger::Application.routes.draw do

  root :to => "sessions#new"

  resource :session, only:[:new, :create, :destroy]
  resources :users do
    resources :photos, only: [:index]
  end

  resources :photos, only: [:index] do
    resources :tags, except: :show
  end
  resource :photo, only: [:new, :create]
  resources :photo, only: [:edit, :update, :show, :destroy]
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id

  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: :friend_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photopath, :user_id

  belongs_to :user
  has_many :tags
  has_many :tagged_users, class_name: "Tag", foreign_key: :user_id

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :photo_id, :user_id, :x_coord, :y_coord

  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :session_token

  has_many :photos
  has_many :friendships, foreign_key: :user_id
  has_many :friends, through: :friendships, source: :friend

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def set_flash(message)
    flash[:notices] ||= []
    flash[:notices] << message
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    params[:photo][:user_id] = current_user.id
    @photo = Photo.new(params[:photo])
    @photo.save

    respond_to do |format|
      format.json { render :json => @photo.to_json}
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
    if params[:user_id]
      @photos = Photo.all
    else
      @photos = Photo.all
    end

    respond_to do |format|
      format.html {render :index}
      format.json {render :json => @photos.to_json}
    end

  end

  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.json {render :json => @photo.to_json}
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_name_and_password_digest(params[:user][:name],
            params[:user][:password_digest])
    if @user
      login @user
      redirect_to user_photos_url(@user)
    else
      set_flash "Error logging in."
      redirect_to new_session_url
    end
  end

  def new
    @user = User.new
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def create
    @tag = Tag.create!(params[:tag])
    respond_to do |format|
      format.json { render :json => @tag.to_json }
    end
  end

  def destroy
  end

  def index
    @tags = Tag.all
    respond_to do |format|
      format.json { render :json => @tags.to_json }
    end
  end

  def edit
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

    if @user.save
      login @user
      redirect_to user_photos_url(@user)
    else
      set_flash "Could not create new user."
      redirect_to new_user_url
    end
  end

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    respond_to do |format|
      format.json {render :json => @users.to_json}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session_token = SecureRandom::urlsafe_base64
    session[:session_token] = session_token
    user.update_attributes(session_token: session_token)
    self.current_user = user
  end

  def logout
    session[:session_token] = nil
    current_user.update_attributes(session_token: nil)
    self.current_user = nil
  end

  def current_user
    if session[:session_token]
      @current_user = User.find_by_session_token(session[:session_token])
    end
  end

  def current_user=(val)
    @current_user = val
  end

  def authenticate
    unless !!current_user
      set_flash "Not authorized."
    end
  end


end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phototagger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
Logged in as: <%= current_user.name %>
<% end %>

<% if flash[:notices] %>
<% flash[:notices].each do |notice| %>
<%= notice %>
<% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

<form action="<%= photos_url %>" method="post">
  <input type="text" name="photo[photopath]">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input class="creation" type="submit" name="submit" value="New Photo">
</form>

<div class="photo">
  <% @photos.each do |photo| %>
  <p><img src="<%= photo.photopath %>"></p>
  <% end %>
</div>

<script>
var x = new PhotosViewController()
</script>

app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

<%= image_tag @photo.photograph.url %>
<%= image_tag @photo.photograph.url(:medium) %>
<%= image_tag @photo.photograph.url(:thumb) %>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">

  <label for = "name">Name</label>
  <input type="text" name="user[name]">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for = "password">Password</label>
  <input type="password" name="user[password_digest]">

  <input type="submit" name="Submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Page</h1>

<%= @user.name %>